spring.application.name=ecom-product
spring.sql.init.mode=always
spring.r2dbc.url=r2dbc:h2:mem:///ecom-product
spring.r2dbc.username=sa
spring.r2dbc.password=

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true
