spring.application.name=ecom-product
spring.main.web-application-type=reactive

db.url=ecom-product-mysql-lb
db.port=33062

spring.r2dbc.url=r2dbc:mysql://${db.url}:${db.port}/product
spring.r2dbc.username=ENC(DJtRk7ioindHBJ9ojbazsL/p4e3SIN6ICGi0G8Wmnyqzrtgg66iKh6Q3G3VS60Xo)
spring.r2dbc.password=ENC(i64a59ARhBMxFntL/ehnEBD5yNqejzwy7tcJ77k9CF1ak4rOSpTybBWFswN+xKx4kDpyeUEzM/oEKj1Ri1ZKYQ==)

spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://${db.url}:${db.port}/product
spring.flyway.user=${spring.r2dbc.username}
spring.flyway.password=${spring.r2dbc.password}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true

spring.messages.encoding=UTF-8

jasypt.encryptor.password=${ENCRYPTION_KEY}
jasypt.encryptor.algorithm=PBEWithHMACSHA512AndAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.key-obtention-iterations=1000

token.jwt.secret=ENC(FgAm9WJeWJZLl/qldDbJHRrraEJXYREQP2tpCjxsCmrCKo6bM3qFB/1K9k6X92ZLos4IoAPooFmbekfxTXOQyw==)

management.endpoints.web.exposure.include=prometheus,threaddump
management.endpoint.prometheus.enabled=true
management.server.port=8081

# WebClient 설정 값
app.stock-api.url=http://ecom-stock-api:18086
app.stock-api.pool-size=100
app.stock-api.pool-acquire-time=3
app.stock-api.pool-idle-time=30
app.stock-api.pool-max-time=60
app.stock-api.pool-evict-time=30
app.stock-api.time-out=3

logging.level.site.ng_archive.ecom_common.logging=trace
logging.level.org.zalando.logbook=trace
logbook.filter.enabled=false
logbook.format.style=json
logbook.write.max-body-size=10240
logbook.obfuscate.json-body-fields[0]=password
logbook.predicate.exclude[0].path=/actuator/**
logbook.predicate.exclude[1].path=/swagger-ui/**
logbook.predicate.exclude[2].path=/apispec*
logbook.predicate.exclude[3].path=/v3/api-docs/*
logbook.predicate.exclude[4].path=/favicon.ico
logbook.obfuscate.headers[0]=Authorization
