spring.application.name=ecom-product
spring.main.web-application-type=reactive

db.url=ecom-product-mysql-lb
db.port=33062

spring.r2dbc.url=r2dbc:mysql://${db.url}:${db.port}/product
spring.r2dbc.username=ENC(DJtRk7ioindHBJ9ojbazsL/p4e3SIN6ICGi0G8Wmnyqzrtgg66iKh6Q3G3VS60Xo)
spring.r2dbc.password=ENC(i64a59ARhBMxFntL/ehnEBD5yNqejzwy7tcJ77k9CF1ak4rOSpTybBWFswN+xKx4kDpyeUEzM/oEKj1Ri1ZKYQ==)

spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://${db.url}:${db.port}/product
spring.flyway.user=${spring.r2dbc.username}
spring.flyway.password=${spring.r2dbc.password}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true

spring.messages.encoding=UTF-8

jasypt.encryptor.password=${ENCRYPTION_KEY}
jasypt.encryptor.algorithm=PBEWithHMACSHA512AndAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.key-obtention-iterations=1000

token.jwt.secret=ENC(FgAm9WJeWJZLl/qldDbJHRrraEJXYREQP2tpCjxsCmrCKo6bM3qFB/1K9k6X92ZLos4IoAPooFmbekfxTXOQyw==)

management.endpoints.web.exposure.include=prometheus,threaddump
management.endpoint.prometheus.enabled=true
management.server.port=8081
